//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigortaMusTakipProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.MusteriGorusme = new HashSet<MusteriGorusme>();
        }
    
        public int Id { get; set; }
        public string MusAdı { get; set; }
        public string MusSoyad { get; set; }
        public string Isyeri { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriGorusme> MusteriGorusme { get; set; }
    }
}
